
services:

  reverse-proxy-test:
    image: traefik:v3.3
    container_name: ${APP}-local-reverse-proxy-container
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/etc/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config:/etc/traefik/config:ro
      - ./traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`tf-dashboard.testlocalsetup.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # Read the Readme 'Basic Auth for traefik dashboard.' section to understand how to generate the password.
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$xyas8m/8$$yL.jrM7BoiY8eqif/4h8T/"
      - "traefik.http.routers.dashboard.middlewares=auth"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s

  # This is a test service to check if the reverse proxy is working.
  whoami:
    image: traefik/whoami
    container_name: ${APP}-local-whoami-container
    networks:
      - proxy
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.testlocalsetup.com`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
    depends_on:
      reverse-proxy-test:
        condition: service_healthy

networks:
  proxy:
    name: test_traefik_proxy
    external: true
