
services:

  reverse-proxy-test:
    image: traefik:v3.3
    container_name: ${APP}-stag-reverse-proxy-container
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - /etc/localtime:/etc/localtime:ro
      - ./traefik-test/traefik.yml:/traefik.yml:ro
      - ./traefik-test/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`tf-dashboard.testlocalsetup.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$xyas8m/8$$yL.jrM7BoiY8eqif/4h8T/"
      - "traefik.http.routers.dashboard.middlewares=auth"


networks:
  proxy:
    name: test_traefik_proxy
    external: true



