
services:

  mkcert:
    build:
      context: .
      dockerfile: Dockerfile.mkcert
    volumes:
      - ./traefik/certs:/certs
    command: >
      sh -c "mkdir -p /root/.local/share/mkcert &&
             CAROOT=/root/.local/share/mkcert mkcert -install &&
             mkcert -cert-file /certs/cert.pem -key-file /certs/key.pem 'tf-dashboard.testlocalsetup.com' '*.testlocalsetup.com' &&
             cp /root/.local/share/mkcert/rootCA.pem /certs/ &&
             chown -R 1000:1000 /certs/*"
    


  reverse-proxy-test:
    image: traefik:v3.3
    container_name: ${APP}-local-reverse-proxy-container
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      # Setup the hosts file with this container ip address and the domain name used for testing.
      # i.e 172.27.0.2  tf-dashboard.testlocalsetup.com
      - "traefik.http.routers.dashboard.rule=Host(`tf-dashboard.testlocalsetup.com`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      # Read the Readme 'Basic Auth for traefik dashboard.' section to understand how to generate the password.
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$xyas8m/8$$yL.jrM7BoiY8eqif/4h8T/"
      - "traefik.http.routers.dashboard.middlewares=auth"


networks:
  proxy:
    name: test_traefik_proxy
    external: true



