
services:
  docusaurus:
    container_name: ${APP}-local-docusaurus-container
    image: nginx:alpine
    networks:
      - proxy
    volumes:
      - ../../sample_app/build:/usr/share/nginx/html
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docusaurus.rule=Host(`docusaurus.testlocalsetup.com`)"
      - "traefik.http.routers.docusaurus.tls=true"
      - "traefik.http.routers.docusaurus.entrypoints=websecure"
      - "traefik.http.services.docusaurus.loadbalancer.server.port=80"
    # depends_on:
    #   reverse-proxy-test:
    #     condition: service_healthy
    #     required: true
    external_links:
      - "${APP}-local-reverse-proxy-container:reverse-proxy-test"

networks:
  proxy:
    name: test_traefik_proxy
    external: true

      