FROM alpine:latest

RUN apk add --no-cache curl && \
    curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64" && \
    chmod +x mkcert-v*-linux-amd64 && \
    mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert

RUN mkdir -p /certs

WORKDIR /certs

