name: ${APP}-app-env


services:

  web:
    image: ghcr.io/marcandreuf/base-images/frontend-node22-pnpm:main
    container_name: ${APP}-stag-web-container
    restart: unless-stopped
    user: node
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`testautomationagency.com`) || Host(`www.testautomationagency.com`)
      - traefik.http.routers.web.entrypoints=http
      - traefik.http.routers.web.middlewares=redirect-to-https
      - traefik.http.routers.webs.rule=Host(`testautomationagency.com`) || Host(`www.testautomationagency.com`)
      - traefik.http.routers.webs.entrypoints=https
      - traefik.http.routers.webs.tls=true
      - traefik.http.routers.webs.tls.certresolver=cloudflare
      - traefik.http.routers.webs.middlewares=redirect-to-non-www
      - traefik.http.services.web.loadbalancer.server.port=${WEB_PORT}
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www.testautomationagency.com/(.*)
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://testautomationagency.com/$${1}
      - traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true
    environment:
      - BACKEND_POCKETBASE_API_URL=http://backend_pocketbase:${POCKETBASE_PORT}
    volumes:
      - ../dist:/home/node/workspace/dist      
      - ../astro.config.js:/home/node/workspace/astro.config.js
      - ../pnpm-lock.yaml:/home/node/workspace/pnpm-lock.yaml
      - ../package.json:/home/node/workspace/package.json
      - ../package-lock.json:/home/node/workspace/package-lock.json
    command: /bin/bash -c "pnpm install && npm install && node ./dist/server/entry.mjs"
    # Debug mode
    # command: >
    #   /bin/sh -c "
    #   trap : TERM INT; sleep infinity & wait"
    depends_on:
      backend_pocketbase:
        condition: service_healthy



networks:
  proxy:
    name: test_traefik_proxy
    external: true
