name: ${APP}-env

services:

  test-env:           
    build:
      context: .
      dockerfile: dockerfile-dev-env
    image: ${APP}-dev-env-img
    container_name: ${APP}-dev-env-container
    user: ubuntu
    volumes:
      - ../:/home/ubuntu/workspace:cached
      - ${HOME}/.local/share/pnpm:/home/ubuntu/.local/share/pnpm:cached
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3
