
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log
  maxAge: 10
  maxBackups: 20
  compress: true

api:
  dashboard: true  
  debug: true
  insecure: false  # Keep this false when using authentication

entryPoints:
  ping:
    address: ":8082"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        domains:
          - main: "*.testlocalsetup.com"
            sans:
              - "*.testlocalsetup.com"

# TODO: Review the security of this and provie a better solution for a local development environment.
# serversTransport:
#   insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:  # Enable File provider
  #   filename: /config.yml
    directory: "/etc/traefik/config"  # Watch all files in this directory
    watch: true  # Automatically reload on changes

ping:
  entryPoint: web

