# Add the dynamic configuration for the docker compose services.
# Try to use this configuration to create a dynamic configuration for the docker compose services and remove labels.
http:
  routers:
    traefik:
      rule: Host(`traefik.localhost`)
      service: api@internal
      tls: true
      entrypoints:
        - websecure
      middlewares:
        - traefik-auth

  middlewares:
    traefik-auth:
      basicauth:
        users:
          - "admin:YWRtaW46JGFwcjEkTktZcndnbXIkcXdHa3Ztb1g2LmRlYWNjREVOcTBGLwoK"
