FROM ubuntu:latest

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

# Default to use the ubuntu user for VS Code Remote-Containers
USER ubuntu
RUN mkdir -p /home/ubuntu/workspace
WORKDIR /home/ubuntu/workspace
